USE [master]
GO
/****** Object:  Database [SelenneDB]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE DATABASE [SelenneDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SelenneDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS02\MSSQL\DATA\SelenneDB.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SelenneDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS02\MSSQL\DATA\SelenneDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [SelenneDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SelenneDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SelenneDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SelenneDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SelenneDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SelenneDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SelenneDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [SelenneDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [SelenneDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SelenneDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SelenneDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SelenneDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SelenneDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SelenneDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SelenneDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SelenneDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SelenneDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SelenneDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SelenneDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SelenneDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SelenneDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SelenneDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SelenneDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SelenneDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SelenneDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SelenneDB] SET  MULTI_USER 
GO
ALTER DATABASE [SelenneDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SelenneDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SelenneDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SelenneDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SelenneDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SelenneDB] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [SelenneDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [SelenneDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [SelenneDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [SelenneDB]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AuditoriaPerfil]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AuditoriaPerfil](
	[AuditoriaID] [int] IDENTITY(1,1) NOT NULL,
	[UsuarioID] [int] NOT NULL,
	[TipoCambio] [nvarchar](50) NOT NULL,
	[CampoModificado] [nvarchar](100) NULL,
	[ValorAnterior] [nvarchar](max) NULL,
	[ValorNuevo] [nvarchar](max) NULL,
	[FechaCambio] [datetime] NULL,
	[Origen] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[AuditoriaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Carrito]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Carrito](
	[CarritoID] [int] IDENTITY(1,1) NOT NULL,
	[UsuarioID] [int] NOT NULL,
	[ProductoID] [int] NOT NULL,
	[Cantidad] [int] NOT NULL,
	[TallaSeleccionada] [nvarchar](10) NULL,
	[ColorSeleccionado] [nvarchar](50) NULL,
	[FechaAgregado] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[CarritoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CategoriasPrincipales]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CategoriasPrincipales](
	[CategoriaPrincipalID] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[Descripcion] [nvarchar](500) NULL,
	[Imagen] [nvarchar](500) NULL,
	[Estado] [nvarchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[CategoriaPrincipalID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Nombre] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Colores]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Colores](
	[ColorID] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NOT NULL,
	[CodigoHex] [nvarchar](7) NULL,
	[Estado] [nvarchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[ColorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Nombre] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CompraDetalles]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CompraDetalles](
	[CompraDetalleID] [int] IDENTITY(1,1) NOT NULL,
	[CompraID] [int] NOT NULL,
	[ProductoID] [int] NOT NULL,
	[Cantidad] [int] NOT NULL,
	[PrecioUnitario] [decimal](18, 2) NOT NULL,
	[Total] [decimal](18, 2) NOT NULL,
	[SKU] [nvarchar](50) NULL,
	[Categoria] [nvarchar](100) NULL,
	[Marca] [nvarchar](100) NULL,
	[Talla] [nvarchar](10) NULL,
	[Color] [nvarchar](50) NULL,
	[Material] [nvarchar](100) NULL,
	[TipoProducto] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[CompraDetalleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Compras]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Compras](
	[CompraID] [int] IDENTITY(1,1) NOT NULL,
	[ProveedorID] [int] NOT NULL,
	[OrdenFactura] [nvarchar](50) NOT NULL,
	[Fecha] [datetime] NULL,
	[Total] [decimal](18, 2) NOT NULL,
	[Estado] [nvarchar](20) NULL,
	[Notas] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[CompraID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[OrdenFactura] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EmailVerifications]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EmailVerifications](
	[VerificationID] [int] IDENTITY(1,1) NOT NULL,
	[UsuarioID] [int] NOT NULL,
	[Token] [nvarchar](500) NOT NULL,
	[ExpiresAt] [datetime] NOT NULL,
	[Verified] [bit] NULL,
	[VerifiedAt] [datetime] NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[VerificationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Token] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Favoritos]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Favoritos](
	[FavoritoID] [int] IDENTITY(1,1) NOT NULL,
	[UsuarioID] [int] NOT NULL,
	[ProductoID] [int] NOT NULL,
	[Nota] [nvarchar](500) NULL,
	[FechaAgregado] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[FavoritoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_Favoritos] UNIQUE NONCLUSTERED 
(
	[UsuarioID] ASC,
	[ProductoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LoginAttempts]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LoginAttempts](
	[AttemptID] [int] IDENTITY(1,1) NOT NULL,
	[UsuarioID] [int] NULL,
	[Email] [nvarchar](100) NULL,
	[AttemptAt] [datetime] NULL,
	[Successful] [bit] NULL,
	[IPAddress] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[AttemptID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Marcas]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Marcas](
	[MarcaID] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[Estado] [nvarchar](20) NULL,
	[Logo] [nvarchar](500) NULL,
	[SitioWeb] [nvarchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[MarcaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Nombre] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Materiales]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Materiales](
	[MaterialID] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[Estado] [nvarchar](20) NULL,
	[Descripcion] [nvarchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaterialID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Nombre] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Notificaciones]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Notificaciones](
	[NotificacionID] [int] IDENTITY(1,1) NOT NULL,
	[UsuarioID] [int] NOT NULL,
	[Titulo] [nvarchar](200) NOT NULL,
	[Mensaje] [nvarchar](max) NOT NULL,
	[Tipo] [nvarchar](50) NULL,
	[Leida] [bit] NULL,
	[FechaCreacion] [datetime] NULL,
	[FechaLeida] [datetime] NULL,
	[Referencia] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[NotificacionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PasswordResetTokens]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PasswordResetTokens](
	[ResetTokenID] [int] IDENTITY(1,1) NOT NULL,
	[UsuarioID] [int] NOT NULL,
	[Token] [nvarchar](500) NOT NULL,
	[ExpiresAt] [datetime] NOT NULL,
	[Used] [bit] NULL,
	[UsedAt] [datetime] NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ResetTokenID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Token] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PedidoDetalles]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PedidoDetalles](
	[PedidoDetalleID] [int] IDENTITY(1,1) NOT NULL,
	[PedidoID] [int] NOT NULL,
	[ProductoID] [int] NOT NULL,
	[TallaID] [int] NULL,
	[ColorID] [int] NULL,
	[Cantidad] [int] NOT NULL,
	[PrecioUnitario] [decimal](18, 2) NOT NULL,
	[Subtotal] [decimal](18, 2) NOT NULL,
	[TallaNombre] [nvarchar](50) NULL,
	[ColorNombre] [nvarchar](50) NULL,
	[ImagenProducto] [nvarchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[PedidoDetalleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Pedidos]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pedidos](
	[PedidoID] [int] IDENTITY(1,1) NOT NULL,
	[ClienteID] [int] NOT NULL,
	[FechaPedido] [datetime] NULL,
	[NombreCliente] [nvarchar](100) NOT NULL,
	[DocumentoCliente] [nvarchar](20) NULL,
	[EmailCliente] [nvarchar](100) NOT NULL,
	[TelefonoCliente] [nvarchar](20) NOT NULL,
	[DireccionEnvio] [nvarchar](255) NOT NULL,
	[Ciudad] [nvarchar](100) NOT NULL,
	[CodigoPostal] [nvarchar](10) NULL,
	[MetodoPago] [nvarchar](50) NOT NULL,
	[NumeroCuenta] [nvarchar](50) NULL,
	[NombreTitular] [nvarchar](100) NULL,
	[Banco] [nvarchar](100) NULL,
	[TipoCuenta] [nvarchar](50) NULL,
	[Subtotal] [decimal](18, 2) NOT NULL,
	[Descuento] [decimal](18, 2) NULL,
	[Envio] [decimal](18, 2) NULL,
	[Total] [decimal](18, 2) NOT NULL,
	[Estado] [nvarchar](20) NULL,
	[NumeroGuia] [nvarchar](50) NULL,
	[Transportadora] [nvarchar](100) NULL,
	[FechaEnvio] [datetime] NULL,
	[FechaEntrega] [datetime] NULL,
	[Notas] [nvarchar](max) NULL,
	[FechaActualizacion] [datetime] NULL,
	[ComprobantePago] [nvarchar](500) NULL,
	[ConfirmacionToken] [nvarchar](100) NULL,
	[NumOrdenCliente] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PedidoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Permissions]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Permissions](
	[PermissionID] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[Descripcion] [nvarchar](255) NULL,
	[Estado] [nvarchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[PermissionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Nombre] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProductoColores]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProductoColores](
	[ProductoColorID] [int] IDENTITY(1,1) NOT NULL,
	[ProductoID] [int] NOT NULL,
	[ColorID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ProductoColorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_ProductoColores] UNIQUE NONCLUSTERED 
(
	[ProductoID] ASC,
	[ColorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProductoImagenes]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProductoImagenes](
	[ProductoImagenID] [int] IDENTITY(1,1) NOT NULL,
	[ProductoID] [int] NOT NULL,
	[URL] [nvarchar](max) NULL,
	[Orden] [int] NULL,
	[ColorNombre] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[ProductoImagenID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProductoMateriales]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProductoMateriales](
	[ProductoMaterialID] [int] IDENTITY(1,1) NOT NULL,
	[ProductoID] [int] NOT NULL,
	[MaterialID] [int] NOT NULL,
	[Porcentaje] [decimal](5, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ProductoMaterialID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_ProductoMateriales] UNIQUE NONCLUSTERED 
(
	[ProductoID] ASC,
	[MaterialID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Productos]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Productos](
	[ProductoID] [int] IDENTITY(1,1) NOT NULL,
	[Codigo] [nvarchar](50) NOT NULL,
	[Nombre] [nvarchar](200) NOT NULL,
	[Descripcion] [nvarchar](max) NULL,
	[DescripcionCorta] [nvarchar](500) NULL,
	[CategoriaPrincipalID] [int] NOT NULL,
	[TipoProductoID] [int] NOT NULL,
	[MarcaID] [int] NOT NULL,
	[PrecioCompra] [decimal](18, 2) NULL,
	[PrecioVenta] [decimal](18, 2) NOT NULL,
	[PrecioOferta] [decimal](18, 2) NULL,
	[Stock] [int] NULL,
	[ImagenPrincipal] [nvarchar](max) NULL,
	[Estado] [nvarchar](20) NULL,
	[FechaCreacion] [datetime] NULL,
	[FechaActualizacion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ProductoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProductoStockVariantes]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProductoStockVariantes](
	[VarianteID] [int] IDENTITY(1,1) NOT NULL,
	[ProductoID] [int] NOT NULL,
	[TallaNombre] [nvarchar](100) NULL,
	[ColorNombre] [nvarchar](100) NULL,
	[Stock] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[VarianteID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProductoTallas]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProductoTallas](
	[ProductoTallaID] [int] IDENTITY(1,1) NOT NULL,
	[ProductoID] [int] NOT NULL,
	[TallaID] [int] NOT NULL,
	[StockTalla] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ProductoTallaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_ProductoTallas] UNIQUE NONCLUSTERED 
(
	[ProductoID] ASC,
	[TallaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Proveedores]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Proveedores](
	[ProveedorID] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](200) NOT NULL,
	[Contacto] [nvarchar](100) NULL,
	[Email] [nvarchar](100) NULL,
	[Telefono] [nvarchar](50) NULL,
	[Documento] [nvarchar](50) NULL,
	[Estado] [nvarchar](20) NULL,
	[FechaRegistro] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ProveedorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RefreshTokens]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RefreshTokens](
	[RefreshTokenID] [int] IDENTITY(1,1) NOT NULL,
	[UsuarioID] [int] NOT NULL,
	[Token] [nvarchar](500) NOT NULL,
	[ExpiresAt] [datetime] NOT NULL,
	[Revoked] [bit] NULL,
	[CreatedAt] [datetime] NULL,
	[RevokedAt] [datetime] NULL,
	[IPAddress] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[RefreshTokenID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Token] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RolePermissions]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RolePermissions](
	[RolePermissionID] [int] IDENTITY(1,1) NOT NULL,
	[RoleID] [int] NOT NULL,
	[PermissionID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[RolePermissionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_RolePermissions] UNIQUE NONCLUSTERED 
(
	[RoleID] ASC,
	[PermissionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Roles]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[RoleID] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NOT NULL,
	[Descripcion] [nvarchar](255) NULL,
	[Estado] [nvarchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[RoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Nombre] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[StockMovimientos]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StockMovimientos](
	[MovimientoID] [int] IDENTITY(1,1) NOT NULL,
	[ProductoID] [int] NOT NULL,
	[Cantidad] [int] NOT NULL,
	[Tipo] [nvarchar](20) NOT NULL,
	[ReferenciaTipo] [nvarchar](50) NULL,
	[ReferenciaID] [int] NULL,
	[Fecha] [datetime] NULL,
	[UsuarioID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[MovimientoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tallas]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tallas](
	[TallaID] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](10) NOT NULL,
	[Orden] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[TallaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Nombre] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TiposProducto]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TiposProducto](
	[TipoProductoID] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[Estado] [nvarchar](20) NULL,
	[Descripcion] [nvarchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[TipoProductoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Nombre] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserSessions]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserSessions](
	[SessionID] [int] IDENTITY(1,1) NOT NULL,
	[UsuarioID] [int] NOT NULL,
	[RefreshTokenID] [int] NULL,
	[UserAgent] [nvarchar](500) NULL,
	[IPAddress] [nvarchar](50) NULL,
	[CreatedAt] [datetime] NULL,
	[LastSeenAt] [datetime] NULL,
	[Revoked] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[SessionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[UsuarioID] [int] IDENTITY(1,1) NOT NULL,
	[NombreCompleto] [nvarchar](100) NOT NULL,
	[Email] [nvarchar](100) NOT NULL,
	[Telefono] [nvarchar](20) NULL,
	[Documento] [nvarchar](20) NULL,
	[Direccion] [nvarchar](255) NULL,
	[PasswordHash] [nvarchar](255) NOT NULL,
	[RoleID] [int] NULL,
	[Estado] [nvarchar](20) NULL,
	[EmailVerificado] [bit] NULL,
	[FechaRegistro] [datetime] NULL,
	[FechaUltimoLogin] [datetime] NULL,
	[Ciudad] [nvarchar](100) NULL,
	[NotificacionesEmail] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UsuarioID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Valoraciones]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Valoraciones](
	[ValoracionID] [int] IDENTITY(1,1) NOT NULL,
	[ProductoID] [int] NOT NULL,
	[UsuarioID] [int] NOT NULL,
	[PedidoID] [int] NULL,
	[Puntuacion] [int] NOT NULL,
	[Comentario] [nvarchar](max) NULL,
	[Util] [int] NULL,
	[NoUtil] [int] NULL,
	[VerificadoCompra] [bit] NULL,
	[FechaCreacion] [datetime] NULL,
	[Estado] [nvarchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[ValoracionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VentaDetalles]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VentaDetalles](
	[VentaDetalleID] [int] IDENTITY(1,1) NOT NULL,
	[VentaID] [int] NOT NULL,
	[ProductoID] [int] NOT NULL,
	[TallaID] [int] NULL,
	[ColorID] [int] NULL,
	[Cantidad] [int] NOT NULL,
	[PrecioUnitario] [decimal](18, 2) NOT NULL,
	[Subtotal] [decimal](18, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[VentaDetalleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Ventas]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ventas](
	[VentaID] [int] IDENTITY(1,1) NOT NULL,
	[UsuarioID] [int] NULL,
	[ClienteID] [int] NULL,
	[FechaVenta] [datetime] NULL,
	[Subtotal] [decimal](18, 2) NOT NULL,
	[Descuento] [decimal](18, 2) NULL,
	[Envio] [decimal](18, 2) NULL,
	[Total] [decimal](18, 2) NOT NULL,
	[Estado] [nvarchar](20) NULL,
	[MetodoPago] [nvarchar](50) NULL,
	[Notas] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[VentaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_AuditoriaPerfil_Usuario]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE NONCLUSTERED INDEX [IX_AuditoriaPerfil_Usuario] ON [dbo].[AuditoriaPerfil]
(
	[UsuarioID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Carrito_Usuario]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE NONCLUSTERED INDEX [IX_Carrito_Usuario] ON [dbo].[Carrito]
(
	[UsuarioID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_CompraDetalles_Compra]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE NONCLUSTERED INDEX [IX_CompraDetalles_Compra] ON [dbo].[CompraDetalles]
(
	[CompraID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Compras_Proveedor]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE NONCLUSTERED INDEX [IX_Compras_Proveedor] ON [dbo].[Compras]
(
	[ProveedorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Favoritos_Usuario]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE NONCLUSTERED INDEX [IX_Favoritos_Usuario] ON [dbo].[Favoritos]
(
	[UsuarioID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_LoginAttempts_Email]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE NONCLUSTERED INDEX [IX_LoginAttempts_Email] ON [dbo].[LoginAttempts]
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Notificaciones_Usuario]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE NONCLUSTERED INDEX [IX_Notificaciones_Usuario] ON [dbo].[Notificaciones]
(
	[UsuarioID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_PedidoDetalles_Pedido]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE NONCLUSTERED INDEX [IX_PedidoDetalles_Pedido] ON [dbo].[PedidoDetalles]
(
	[PedidoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Pedidos_Cliente]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE NONCLUSTERED INDEX [IX_Pedidos_Cliente] ON [dbo].[Pedidos]
(
	[ClienteID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Pedidos_Estado]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE NONCLUSTERED INDEX [IX_Pedidos_Estado] ON [dbo].[Pedidos]
(
	[Estado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Productos_Categoria]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE NONCLUSTERED INDEX [IX_Productos_Categoria] ON [dbo].[Productos]
(
	[CategoriaPrincipalID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Productos_Codigo]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE NONCLUSTERED INDEX [IX_Productos_Codigo] ON [dbo].[Productos]
(
	[Codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Productos_Estado]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE NONCLUSTERED INDEX [IX_Productos_Estado] ON [dbo].[Productos]
(
	[Estado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_StockVariantes_Producto]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE NONCLUSTERED INDEX [IX_StockVariantes_Producto] ON [dbo].[ProductoStockVariantes]
(
	[ProductoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_RefreshTokens_Revoked]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE NONCLUSTERED INDEX [IX_RefreshTokens_Revoked] ON [dbo].[RefreshTokens]
(
	[Revoked] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_RefreshTokens_UsuarioID]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE NONCLUSTERED INDEX [IX_RefreshTokens_UsuarioID] ON [dbo].[RefreshTokens]
(
	[UsuarioID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_StockMovimientos_Producto]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE NONCLUSTERED INDEX [IX_StockMovimientos_Producto] ON [dbo].[StockMovimientos]
(
	[ProductoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_UserSessions_UsuarioID]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE NONCLUSTERED INDEX [IX_UserSessions_UsuarioID] ON [dbo].[UserSessions]
(
	[UsuarioID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Usuarios_Email]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE NONCLUSTERED INDEX [IX_Usuarios_Email] ON [dbo].[Usuarios]
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Valoraciones_Producto]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE NONCLUSTERED INDEX [IX_Valoraciones_Producto] ON [dbo].[Valoraciones]
(
	[ProductoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Valoraciones_Usuario]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE NONCLUSTERED INDEX [IX_Valoraciones_Usuario] ON [dbo].[Valoraciones]
(
	[UsuarioID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Ventas_Cliente]    Script Date: 1/07/2026 9:14:38 a. m. ******/
CREATE NONCLUSTERED INDEX [IX_Ventas_Cliente] ON [dbo].[Ventas]
(
	[ClienteID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AuditoriaPerfil] ADD  DEFAULT (getdate()) FOR [FechaCambio]
GO
ALTER TABLE [dbo].[Carrito] ADD  DEFAULT ((1)) FOR [Cantidad]
GO
ALTER TABLE [dbo].[Carrito] ADD  DEFAULT (getdate()) FOR [FechaAgregado]
GO
ALTER TABLE [dbo].[CategoriasPrincipales] ADD  DEFAULT ('activo') FOR [Estado]
GO
ALTER TABLE [dbo].[Colores] ADD  DEFAULT ('activo') FOR [Estado]
GO
ALTER TABLE [dbo].[Compras] ADD  DEFAULT (getdate()) FOR [Fecha]
GO
ALTER TABLE [dbo].[Compras] ADD  DEFAULT ('Activa') FOR [Estado]
GO
ALTER TABLE [dbo].[EmailVerifications] ADD  DEFAULT ((0)) FOR [Verified]
GO
ALTER TABLE [dbo].[EmailVerifications] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[Favoritos] ADD  DEFAULT (getdate()) FOR [FechaAgregado]
GO
ALTER TABLE [dbo].[LoginAttempts] ADD  DEFAULT (getdate()) FOR [AttemptAt]
GO
ALTER TABLE [dbo].[LoginAttempts] ADD  DEFAULT ((0)) FOR [Successful]
GO
ALTER TABLE [dbo].[Marcas] ADD  DEFAULT ('activo') FOR [Estado]
GO
ALTER TABLE [dbo].[Materiales] ADD  DEFAULT ('activo') FOR [Estado]
GO
ALTER TABLE [dbo].[Notificaciones] ADD  DEFAULT ('info') FOR [Tipo]
GO
ALTER TABLE [dbo].[Notificaciones] ADD  DEFAULT ((0)) FOR [Leida]
GO
ALTER TABLE [dbo].[Notificaciones] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [dbo].[PasswordResetTokens] ADD  DEFAULT ((0)) FOR [Used]
GO
ALTER TABLE [dbo].[PasswordResetTokens] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[Pedidos] ADD  DEFAULT (getdate()) FOR [FechaPedido]
GO
ALTER TABLE [dbo].[Pedidos] ADD  DEFAULT ((0)) FOR [Descuento]
GO
ALTER TABLE [dbo].[Pedidos] ADD  DEFAULT ((0)) FOR [Envio]
GO
ALTER TABLE [dbo].[Pedidos] ADD  DEFAULT ('Pendiente') FOR [Estado]
GO
ALTER TABLE [dbo].[Pedidos] ADD  DEFAULT (getdate()) FOR [FechaActualizacion]
GO
ALTER TABLE [dbo].[Pedidos] ADD  DEFAULT ((1)) FOR [NumOrdenCliente]
GO
ALTER TABLE [dbo].[Permissions] ADD  DEFAULT ('activo') FOR [Estado]
GO
ALTER TABLE [dbo].[ProductoImagenes] ADD  DEFAULT ((0)) FOR [Orden]
GO
ALTER TABLE [dbo].[Productos] ADD  DEFAULT ((0)) FOR [Stock]
GO
ALTER TABLE [dbo].[Productos] ADD  DEFAULT ('activo') FOR [Estado]
GO
ALTER TABLE [dbo].[Productos] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [dbo].[Productos] ADD  DEFAULT (getdate()) FOR [FechaActualizacion]
GO
ALTER TABLE [dbo].[ProductoStockVariantes] ADD  DEFAULT ((0)) FOR [Stock]
GO
ALTER TABLE [dbo].[ProductoTallas] ADD  DEFAULT ((0)) FOR [StockTalla]
GO
ALTER TABLE [dbo].[Proveedores] ADD  DEFAULT ('activo') FOR [Estado]
GO
ALTER TABLE [dbo].[Proveedores] ADD  DEFAULT (getdate()) FOR [FechaRegistro]
GO
ALTER TABLE [dbo].[RefreshTokens] ADD  DEFAULT ((0)) FOR [Revoked]
GO
ALTER TABLE [dbo].[RefreshTokens] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[Roles] ADD  DEFAULT ('activo') FOR [Estado]
GO
ALTER TABLE [dbo].[StockMovimientos] ADD  DEFAULT (getdate()) FOR [Fecha]
GO
ALTER TABLE [dbo].[Tallas] ADD  DEFAULT ((0)) FOR [Orden]
GO
ALTER TABLE [dbo].[TiposProducto] ADD  DEFAULT ('activo') FOR [Estado]
GO
ALTER TABLE [dbo].[UserSessions] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[UserSessions] ADD  DEFAULT (getdate()) FOR [LastSeenAt]
GO
ALTER TABLE [dbo].[UserSessions] ADD  DEFAULT ((0)) FOR [Revoked]
GO
ALTER TABLE [dbo].[Usuarios] ADD  DEFAULT ('activo') FOR [Estado]
GO
ALTER TABLE [dbo].[Usuarios] ADD  DEFAULT ((0)) FOR [EmailVerificado]
GO
ALTER TABLE [dbo].[Usuarios] ADD  DEFAULT (getdate()) FOR [FechaRegistro]
GO
ALTER TABLE [dbo].[Usuarios] ADD  DEFAULT ((1)) FOR [NotificacionesEmail]
GO
ALTER TABLE [dbo].[Valoraciones] ADD  DEFAULT ((0)) FOR [Util]
GO
ALTER TABLE [dbo].[Valoraciones] ADD  DEFAULT ((0)) FOR [NoUtil]
GO
ALTER TABLE [dbo].[Valoraciones] ADD  DEFAULT ((0)) FOR [VerificadoCompra]
GO
ALTER TABLE [dbo].[Valoraciones] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [dbo].[Valoraciones] ADD  DEFAULT ('pendiente') FOR [Estado]
GO
ALTER TABLE [dbo].[Ventas] ADD  DEFAULT (getdate()) FOR [FechaVenta]
GO
ALTER TABLE [dbo].[Ventas] ADD  DEFAULT ((0)) FOR [Descuento]
GO
ALTER TABLE [dbo].[Ventas] ADD  DEFAULT ((0)) FOR [Envio]
GO
ALTER TABLE [dbo].[Ventas] ADD  DEFAULT ('Pendiente') FOR [Estado]
GO
ALTER TABLE [dbo].[AuditoriaPerfil]  WITH CHECK ADD  CONSTRAINT [FK_AuditoriaPerfil_Usuarios] FOREIGN KEY([UsuarioID])
REFERENCES [dbo].[Usuarios] ([UsuarioID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AuditoriaPerfil] CHECK CONSTRAINT [FK_AuditoriaPerfil_Usuarios]
GO
ALTER TABLE [dbo].[Carrito]  WITH CHECK ADD  CONSTRAINT [FK_Carrito_Productos] FOREIGN KEY([ProductoID])
REFERENCES [dbo].[Productos] ([ProductoID])
GO
ALTER TABLE [dbo].[Carrito] CHECK CONSTRAINT [FK_Carrito_Productos]
GO
ALTER TABLE [dbo].[Carrito]  WITH CHECK ADD  CONSTRAINT [FK_Carrito_Usuarios] FOREIGN KEY([UsuarioID])
REFERENCES [dbo].[Usuarios] ([UsuarioID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Carrito] CHECK CONSTRAINT [FK_Carrito_Usuarios]
GO
ALTER TABLE [dbo].[CompraDetalles]  WITH CHECK ADD  CONSTRAINT [FK_CompraDetalles_Compras] FOREIGN KEY([CompraID])
REFERENCES [dbo].[Compras] ([CompraID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CompraDetalles] CHECK CONSTRAINT [FK_CompraDetalles_Compras]
GO
ALTER TABLE [dbo].[CompraDetalles]  WITH CHECK ADD  CONSTRAINT [FK_CompraDetalles_Productos] FOREIGN KEY([ProductoID])
REFERENCES [dbo].[Productos] ([ProductoID])
GO
ALTER TABLE [dbo].[CompraDetalles] CHECK CONSTRAINT [FK_CompraDetalles_Productos]
GO
ALTER TABLE [dbo].[Compras]  WITH CHECK ADD  CONSTRAINT [FK_Compras_Proveedores] FOREIGN KEY([ProveedorID])
REFERENCES [dbo].[Proveedores] ([ProveedorID])
GO
ALTER TABLE [dbo].[Compras] CHECK CONSTRAINT [FK_Compras_Proveedores]
GO
ALTER TABLE [dbo].[EmailVerifications]  WITH CHECK ADD  CONSTRAINT [FK_EmailVerifications_Usuarios] FOREIGN KEY([UsuarioID])
REFERENCES [dbo].[Usuarios] ([UsuarioID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[EmailVerifications] CHECK CONSTRAINT [FK_EmailVerifications_Usuarios]
GO
ALTER TABLE [dbo].[Favoritos]  WITH CHECK ADD  CONSTRAINT [FK_Favoritos_Productos] FOREIGN KEY([ProductoID])
REFERENCES [dbo].[Productos] ([ProductoID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Favoritos] CHECK CONSTRAINT [FK_Favoritos_Productos]
GO
ALTER TABLE [dbo].[Favoritos]  WITH CHECK ADD  CONSTRAINT [FK_Favoritos_Usuarios] FOREIGN KEY([UsuarioID])
REFERENCES [dbo].[Usuarios] ([UsuarioID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Favoritos] CHECK CONSTRAINT [FK_Favoritos_Usuarios]
GO
ALTER TABLE [dbo].[LoginAttempts]  WITH CHECK ADD  CONSTRAINT [FK_LoginAttempts_Usuarios] FOREIGN KEY([UsuarioID])
REFERENCES [dbo].[Usuarios] ([UsuarioID])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[LoginAttempts] CHECK CONSTRAINT [FK_LoginAttempts_Usuarios]
GO
ALTER TABLE [dbo].[Notificaciones]  WITH CHECK ADD  CONSTRAINT [FK_Notificaciones_Usuarios] FOREIGN KEY([UsuarioID])
REFERENCES [dbo].[Usuarios] ([UsuarioID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Notificaciones] CHECK CONSTRAINT [FK_Notificaciones_Usuarios]
GO
ALTER TABLE [dbo].[PasswordResetTokens]  WITH CHECK ADD  CONSTRAINT [FK_PasswordResetTokens_Usuarios] FOREIGN KEY([UsuarioID])
REFERENCES [dbo].[Usuarios] ([UsuarioID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PasswordResetTokens] CHECK CONSTRAINT [FK_PasswordResetTokens_Usuarios]
GO
ALTER TABLE [dbo].[PedidoDetalles]  WITH CHECK ADD  CONSTRAINT [FK_PedidoDetalles_Colores] FOREIGN KEY([ColorID])
REFERENCES [dbo].[Colores] ([ColorID])
GO
ALTER TABLE [dbo].[PedidoDetalles] CHECK CONSTRAINT [FK_PedidoDetalles_Colores]
GO
ALTER TABLE [dbo].[PedidoDetalles]  WITH CHECK ADD  CONSTRAINT [FK_PedidoDetalles_Pedidos] FOREIGN KEY([PedidoID])
REFERENCES [dbo].[Pedidos] ([PedidoID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PedidoDetalles] CHECK CONSTRAINT [FK_PedidoDetalles_Pedidos]
GO
ALTER TABLE [dbo].[PedidoDetalles]  WITH CHECK ADD  CONSTRAINT [FK_PedidoDetalles_Productos] FOREIGN KEY([ProductoID])
REFERENCES [dbo].[Productos] ([ProductoID])
GO
ALTER TABLE [dbo].[PedidoDetalles] CHECK CONSTRAINT [FK_PedidoDetalles_Productos]
GO
ALTER TABLE [dbo].[PedidoDetalles]  WITH CHECK ADD  CONSTRAINT [FK_PedidoDetalles_Tallas] FOREIGN KEY([TallaID])
REFERENCES [dbo].[Tallas] ([TallaID])
GO
ALTER TABLE [dbo].[PedidoDetalles] CHECK CONSTRAINT [FK_PedidoDetalles_Tallas]
GO
ALTER TABLE [dbo].[Pedidos]  WITH CHECK ADD  CONSTRAINT [FK_Pedidos_Clientes] FOREIGN KEY([ClienteID])
REFERENCES [dbo].[Usuarios] ([UsuarioID])
GO
ALTER TABLE [dbo].[Pedidos] CHECK CONSTRAINT [FK_Pedidos_Clientes]
GO
ALTER TABLE [dbo].[ProductoColores]  WITH CHECK ADD  CONSTRAINT [FK_ProductoColores_Colores] FOREIGN KEY([ColorID])
REFERENCES [dbo].[Colores] ([ColorID])
GO
ALTER TABLE [dbo].[ProductoColores] CHECK CONSTRAINT [FK_ProductoColores_Colores]
GO
ALTER TABLE [dbo].[ProductoColores]  WITH CHECK ADD  CONSTRAINT [FK_ProductoColores_Productos] FOREIGN KEY([ProductoID])
REFERENCES [dbo].[Productos] ([ProductoID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ProductoColores] CHECK CONSTRAINT [FK_ProductoColores_Productos]
GO
ALTER TABLE [dbo].[ProductoImagenes]  WITH CHECK ADD  CONSTRAINT [FK_ProductoImagenes_Productos] FOREIGN KEY([ProductoID])
REFERENCES [dbo].[Productos] ([ProductoID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ProductoImagenes] CHECK CONSTRAINT [FK_ProductoImagenes_Productos]
GO
ALTER TABLE [dbo].[ProductoMateriales]  WITH CHECK ADD  CONSTRAINT [FK_ProductoMateriales_Materiales] FOREIGN KEY([MaterialID])
REFERENCES [dbo].[Materiales] ([MaterialID])
GO
ALTER TABLE [dbo].[ProductoMateriales] CHECK CONSTRAINT [FK_ProductoMateriales_Materiales]
GO
ALTER TABLE [dbo].[ProductoMateriales]  WITH CHECK ADD  CONSTRAINT [FK_ProductoMateriales_Productos] FOREIGN KEY([ProductoID])
REFERENCES [dbo].[Productos] ([ProductoID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ProductoMateriales] CHECK CONSTRAINT [FK_ProductoMateriales_Productos]
GO
ALTER TABLE [dbo].[Productos]  WITH CHECK ADD  CONSTRAINT [FK_Productos_Categoria] FOREIGN KEY([CategoriaPrincipalID])
REFERENCES [dbo].[CategoriasPrincipales] ([CategoriaPrincipalID])
GO
ALTER TABLE [dbo].[Productos] CHECK CONSTRAINT [FK_Productos_Categoria]
GO
ALTER TABLE [dbo].[Productos]  WITH CHECK ADD  CONSTRAINT [FK_Productos_Marca] FOREIGN KEY([MarcaID])
REFERENCES [dbo].[Marcas] ([MarcaID])
GO
ALTER TABLE [dbo].[Productos] CHECK CONSTRAINT [FK_Productos_Marca]
GO
ALTER TABLE [dbo].[Productos]  WITH CHECK ADD  CONSTRAINT [FK_Productos_Tipo] FOREIGN KEY([TipoProductoID])
REFERENCES [dbo].[TiposProducto] ([TipoProductoID])
GO
ALTER TABLE [dbo].[Productos] CHECK CONSTRAINT [FK_Productos_Tipo]
GO
ALTER TABLE [dbo].[ProductoStockVariantes]  WITH CHECK ADD  CONSTRAINT [FK_StockVariantes_Producto] FOREIGN KEY([ProductoID])
REFERENCES [dbo].[Productos] ([ProductoID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ProductoStockVariantes] CHECK CONSTRAINT [FK_StockVariantes_Producto]
GO
ALTER TABLE [dbo].[ProductoTallas]  WITH CHECK ADD  CONSTRAINT [FK_ProductoTallas_Productos] FOREIGN KEY([ProductoID])
REFERENCES [dbo].[Productos] ([ProductoID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ProductoTallas] CHECK CONSTRAINT [FK_ProductoTallas_Productos]
GO
ALTER TABLE [dbo].[ProductoTallas]  WITH CHECK ADD  CONSTRAINT [FK_ProductoTallas_Tallas] FOREIGN KEY([TallaID])
REFERENCES [dbo].[Tallas] ([TallaID])
GO
ALTER TABLE [dbo].[ProductoTallas] CHECK CONSTRAINT [FK_ProductoTallas_Tallas]
GO
ALTER TABLE [dbo].[RefreshTokens]  WITH CHECK ADD  CONSTRAINT [FK_RefreshTokens_Usuarios] FOREIGN KEY([UsuarioID])
REFERENCES [dbo].[Usuarios] ([UsuarioID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[RefreshTokens] CHECK CONSTRAINT [FK_RefreshTokens_Usuarios]
GO
ALTER TABLE [dbo].[RolePermissions]  WITH CHECK ADD  CONSTRAINT [FK_RolePermissions_Permissions] FOREIGN KEY([PermissionID])
REFERENCES [dbo].[Permissions] ([PermissionID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[RolePermissions] CHECK CONSTRAINT [FK_RolePermissions_Permissions]
GO
ALTER TABLE [dbo].[RolePermissions]  WITH CHECK ADD  CONSTRAINT [FK_RolePermissions_Roles] FOREIGN KEY([RoleID])
REFERENCES [dbo].[Roles] ([RoleID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[RolePermissions] CHECK CONSTRAINT [FK_RolePermissions_Roles]
GO
ALTER TABLE [dbo].[StockMovimientos]  WITH CHECK ADD  CONSTRAINT [FK_StockMovimientos_Productos] FOREIGN KEY([ProductoID])
REFERENCES [dbo].[Productos] ([ProductoID])
GO
ALTER TABLE [dbo].[StockMovimientos] CHECK CONSTRAINT [FK_StockMovimientos_Productos]
GO
ALTER TABLE [dbo].[UserSessions]  WITH CHECK ADD  CONSTRAINT [FK_UserSessions_RefreshTokens] FOREIGN KEY([RefreshTokenID])
REFERENCES [dbo].[RefreshTokens] ([RefreshTokenID])
GO
ALTER TABLE [dbo].[UserSessions] CHECK CONSTRAINT [FK_UserSessions_RefreshTokens]
GO
ALTER TABLE [dbo].[UserSessions]  WITH CHECK ADD  CONSTRAINT [FK_UserSessions_Usuarios] FOREIGN KEY([UsuarioID])
REFERENCES [dbo].[Usuarios] ([UsuarioID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UserSessions] CHECK CONSTRAINT [FK_UserSessions_Usuarios]
GO
ALTER TABLE [dbo].[Usuarios]  WITH CHECK ADD  CONSTRAINT [FK_Usuarios_Roles] FOREIGN KEY([RoleID])
REFERENCES [dbo].[Roles] ([RoleID])
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[Usuarios] CHECK CONSTRAINT [FK_Usuarios_Roles]
GO
ALTER TABLE [dbo].[Valoraciones]  WITH CHECK ADD  CONSTRAINT [FK_Valoraciones_Pedidos] FOREIGN KEY([PedidoID])
REFERENCES [dbo].[Pedidos] ([PedidoID])
GO
ALTER TABLE [dbo].[Valoraciones] CHECK CONSTRAINT [FK_Valoraciones_Pedidos]
GO
ALTER TABLE [dbo].[Valoraciones]  WITH CHECK ADD  CONSTRAINT [FK_Valoraciones_Productos] FOREIGN KEY([ProductoID])
REFERENCES [dbo].[Productos] ([ProductoID])
GO
ALTER TABLE [dbo].[Valoraciones] CHECK CONSTRAINT [FK_Valoraciones_Productos]
GO
ALTER TABLE [dbo].[Valoraciones]  WITH CHECK ADD  CONSTRAINT [FK_Valoraciones_Usuarios] FOREIGN KEY([UsuarioID])
REFERENCES [dbo].[Usuarios] ([UsuarioID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Valoraciones] CHECK CONSTRAINT [FK_Valoraciones_Usuarios]
GO
ALTER TABLE [dbo].[VentaDetalles]  WITH CHECK ADD  CONSTRAINT [FK_VentaDetalles_Colores] FOREIGN KEY([ColorID])
REFERENCES [dbo].[Colores] ([ColorID])
GO
ALTER TABLE [dbo].[VentaDetalles] CHECK CONSTRAINT [FK_VentaDetalles_Colores]
GO
ALTER TABLE [dbo].[VentaDetalles]  WITH CHECK ADD  CONSTRAINT [FK_VentaDetalles_Productos] FOREIGN KEY([ProductoID])
REFERENCES [dbo].[Productos] ([ProductoID])
GO
ALTER TABLE [dbo].[VentaDetalles] CHECK CONSTRAINT [FK_VentaDetalles_Productos]
GO
ALTER TABLE [dbo].[VentaDetalles]  WITH CHECK ADD  CONSTRAINT [FK_VentaDetalles_Tallas] FOREIGN KEY([TallaID])
REFERENCES [dbo].[Tallas] ([TallaID])
GO
ALTER TABLE [dbo].[VentaDetalles] CHECK CONSTRAINT [FK_VentaDetalles_Tallas]
GO
ALTER TABLE [dbo].[VentaDetalles]  WITH CHECK ADD  CONSTRAINT [FK_VentaDetalles_Ventas] FOREIGN KEY([VentaID])
REFERENCES [dbo].[Ventas] ([VentaID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[VentaDetalles] CHECK CONSTRAINT [FK_VentaDetalles_Ventas]
GO
ALTER TABLE [dbo].[Ventas]  WITH CHECK ADD  CONSTRAINT [FK_Ventas_Clientes] FOREIGN KEY([ClienteID])
REFERENCES [dbo].[Usuarios] ([UsuarioID])
GO
ALTER TABLE [dbo].[Ventas] CHECK CONSTRAINT [FK_Ventas_Clientes]
GO
ALTER TABLE [dbo].[Ventas]  WITH CHECK ADD  CONSTRAINT [FK_Ventas_Usuarios] FOREIGN KEY([UsuarioID])
REFERENCES [dbo].[Usuarios] ([UsuarioID])
GO
ALTER TABLE [dbo].[Ventas] CHECK CONSTRAINT [FK_Ventas_Usuarios]
GO
ALTER TABLE [dbo].[AuditoriaPerfil]  WITH CHECK ADD  CONSTRAINT [CK_AuditoriaPerfil_Tipo] CHECK  (([TipoCambio]='estado' OR [TipoCambio]='pedido' OR [TipoCambio]='contraseña' OR [TipoCambio]='direccion' OR [TipoCambio]='telefono' OR [TipoCambio]='email' OR [TipoCambio]='perfil'))
GO
ALTER TABLE [dbo].[AuditoriaPerfil] CHECK CONSTRAINT [CK_AuditoriaPerfil_Tipo]
GO
ALTER TABLE [dbo].[Carrito]  WITH CHECK ADD  CONSTRAINT [CK_Carrito_Cantidad] CHECK  (([Cantidad]>(0)))
GO
ALTER TABLE [dbo].[Carrito] CHECK CONSTRAINT [CK_Carrito_Cantidad]
GO
ALTER TABLE [dbo].[CategoriasPrincipales]  WITH CHECK ADD  CONSTRAINT [CK_Categorias_Estado] CHECK  (([Estado]='inactivo' OR [Estado]='activo'))
GO
ALTER TABLE [dbo].[CategoriasPrincipales] CHECK CONSTRAINT [CK_Categorias_Estado]
GO
ALTER TABLE [dbo].[Colores]  WITH CHECK ADD  CONSTRAINT [CK_Colores_Estado] CHECK  (([Estado]='inactivo' OR [Estado]='activo'))
GO
ALTER TABLE [dbo].[Colores] CHECK CONSTRAINT [CK_Colores_Estado]
GO
ALTER TABLE [dbo].[CompraDetalles]  WITH CHECK ADD  CONSTRAINT [CK_CompraDetalles_Cantidad] CHECK  (([Cantidad]>(0)))
GO
ALTER TABLE [dbo].[CompraDetalles] CHECK CONSTRAINT [CK_CompraDetalles_Cantidad]
GO
ALTER TABLE [dbo].[Marcas]  WITH CHECK ADD  CONSTRAINT [CK_Marcas_Estado] CHECK  (([Estado]='inactivo' OR [Estado]='activo'))
GO
ALTER TABLE [dbo].[Marcas] CHECK CONSTRAINT [CK_Marcas_Estado]
GO
ALTER TABLE [dbo].[Materiales]  WITH CHECK ADD  CONSTRAINT [CK_Materiales_Estado] CHECK  (([Estado]='inactivo' OR [Estado]='activo'))
GO
ALTER TABLE [dbo].[Materiales] CHECK CONSTRAINT [CK_Materiales_Estado]
GO
ALTER TABLE [dbo].[PedidoDetalles]  WITH CHECK ADD  CONSTRAINT [CK_PedidoDetalles_Cantidad] CHECK  (([Cantidad]>(0)))
GO
ALTER TABLE [dbo].[PedidoDetalles] CHECK CONSTRAINT [CK_PedidoDetalles_Cantidad]
GO
ALTER TABLE [dbo].[Pedidos]  WITH CHECK ADD  CONSTRAINT [CK_Pedidos_Estado] CHECK  (([Estado]='Completada' OR [Estado]='Completado' OR [Estado]='Rechazada' OR [Estado]='Rechazado' OR [Estado]='Cancelado' OR [Estado]='Entregado' OR [Estado]='Enviado' OR [Estado]='En proceso' OR [Estado]='Aprobada' OR [Estado]='Aprobado' OR [Estado]='Pendiente'))
GO
ALTER TABLE [dbo].[Pedidos] CHECK CONSTRAINT [CK_Pedidos_Estado]
GO
ALTER TABLE [dbo].[Permissions]  WITH CHECK ADD  CONSTRAINT [CK_Permissions_Estado] CHECK  (([Estado]='inactivo' OR [Estado]='activo'))
GO
ALTER TABLE [dbo].[Permissions] CHECK CONSTRAINT [CK_Permissions_Estado]
GO
ALTER TABLE [dbo].[Productos]  WITH CHECK ADD  CONSTRAINT [CK_Productos_Estado] CHECK  (([Estado]='inactivo' OR [Estado]='activo'))
GO
ALTER TABLE [dbo].[Productos] CHECK CONSTRAINT [CK_Productos_Estado]
GO
ALTER TABLE [dbo].[Productos]  WITH CHECK ADD  CONSTRAINT [CK_Productos_Precios] CHECK  (([PrecioVenta]>(0)))
GO
ALTER TABLE [dbo].[Productos] CHECK CONSTRAINT [CK_Productos_Precios]
GO
ALTER TABLE [dbo].[Proveedores]  WITH CHECK ADD  CONSTRAINT [CK_Proveedores_Estado] CHECK  (([Estado]='inactivo' OR [Estado]='activo'))
GO
ALTER TABLE [dbo].[Proveedores] CHECK CONSTRAINT [CK_Proveedores_Estado]
GO
ALTER TABLE [dbo].[Roles]  WITH CHECK ADD  CONSTRAINT [CK_Roles_Estado] CHECK  (([Estado]='inactivo' OR [Estado]='activo'))
GO
ALTER TABLE [dbo].[Roles] CHECK CONSTRAINT [CK_Roles_Estado]
GO
ALTER TABLE [dbo].[StockMovimientos]  WITH CHECK ADD  CONSTRAINT [CK_StockMovimientos_Tipo] CHECK  (([Tipo]='salida' OR [Tipo]='entrada'))
GO
ALTER TABLE [dbo].[StockMovimientos] CHECK CONSTRAINT [CK_StockMovimientos_Tipo]
GO
ALTER TABLE [dbo].[TiposProducto]  WITH CHECK ADD  CONSTRAINT [CK_TiposProducto_Estado] CHECK  (([Estado]='inactivo' OR [Estado]='activo'))
GO
ALTER TABLE [dbo].[TiposProducto] CHECK CONSTRAINT [CK_TiposProducto_Estado]
GO
ALTER TABLE [dbo].[Usuarios]  WITH CHECK ADD  CONSTRAINT [CK_Usuarios_Estado] CHECK  (([Estado]='eliminado' OR [Estado]='inactivo' OR [Estado]='activo'))
GO
ALTER TABLE [dbo].[Usuarios] CHECK CONSTRAINT [CK_Usuarios_Estado]
GO
ALTER TABLE [dbo].[Valoraciones]  WITH CHECK ADD CHECK  (([Puntuacion]>=(1) AND [Puntuacion]<=(5)))
GO
ALTER TABLE [dbo].[Valoraciones]  WITH CHECK ADD  CONSTRAINT [CK_Valoraciones_Estado] CHECK  (([Estado]='rechazada' OR [Estado]='aprobada' OR [Estado]='pendiente'))
GO
ALTER TABLE [dbo].[Valoraciones] CHECK CONSTRAINT [CK_Valoraciones_Estado]
GO
ALTER TABLE [dbo].[VentaDetalles]  WITH CHECK ADD  CONSTRAINT [CK_VentaDetalles_Cantidad] CHECK  (([Cantidad]>(0)))
GO
ALTER TABLE [dbo].[VentaDetalles] CHECK CONSTRAINT [CK_VentaDetalles_Cantidad]
GO
ALTER TABLE [dbo].[Ventas]  WITH CHECK ADD  CONSTRAINT [CK_Ventas_Estado] CHECK  (([Estado]='Entregado' OR [Estado]='Enviado' OR [Estado]='En proceso' OR [Estado]='Cancelada' OR [Estado]='Completada' OR [Estado]='Pendiente'))
GO
ALTER TABLE [dbo].[Ventas] CHECK CONSTRAINT [CK_Ventas_Estado]
GO
/****** Object:  StoredProcedure [dbo].[sp_ActualizarEstadoPedido]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[sp_ActualizarEstadoPedido]
    @PedidoID INT,
    @NuevoEstado NVARCHAR(20),
    @Notas NVARCHAR(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION;
    BEGIN TRY
        DECLARE @EstadoAnterior NVARCHAR(20);
        DECLARE @ClienteID INT;
        SELECT @EstadoAnterior = Estado, @ClienteID = ClienteID
        FROM Pedidos WHERE PedidoID = @PedidoID;

        UPDATE Pedidos
        SET Estado = @NuevoEstado,
            Notas = ISNULL(@Notas, Notas),
            FechaActualizacion = GETDATE()
        WHERE PedidoID = @PedidoID;

        INSERT INTO AuditoriaPerfil (
            UsuarioID, TipoCambio, CampoModificado, ValorAnterior, ValorNuevo, Origen
        )
        VALUES (
            @ClienteID, 'pedido', 'Estado', @EstadoAnterior, @NuevoEstado, 'sistema'
        );

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        RAISERROR('Error al actualizar pedido', 16, 1);
    END CATCH
END;
GO
/****** Object:  StoredProcedure [dbo].[sp_AgregarAlCarrito]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[sp_AgregarAlCarrito]
    @UsuarioID INT,
    @ProductoID INT,
    @Cantidad INT,
    @TallaSeleccionada NVARCHAR(10) = NULL,
    @ColorSeleccionado NVARCHAR(50) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION;
    BEGIN TRY
        DECLARE @StockDisponible INT;
        SELECT @StockDisponible = Stock FROM Productos WHERE ProductoID = @ProductoID;
        IF @StockDisponible < @Cantidad
        BEGIN
            RAISERROR('Stock insuficiente', 16, 1);
            RETURN;
        END
        IF EXISTS (
            SELECT 1 FROM Carrito
            WHERE UsuarioID = @UsuarioID AND ProductoID = @ProductoID
              AND ISNULL(TallaSeleccionada,'') = ISNULL(@TallaSeleccionada,'')
              AND ISNULL(ColorSeleccionado,'') = ISNULL(@ColorSeleccionado,'')
        )
        BEGIN
            UPDATE Carrito
            SET Cantidad = Cantidad + @Cantidad, FechaAgregado = GETDATE()
            WHERE UsuarioID = @UsuarioID AND ProductoID = @ProductoID
              AND ISNULL(TallaSeleccionada,'') = ISNULL(@TallaSeleccionada,'')
              AND ISNULL(ColorSeleccionado,'') = ISNULL(@ColorSeleccionado,'');
        END
        ELSE
        BEGIN
            INSERT INTO Carrito (UsuarioID, ProductoID, Cantidad, TallaSeleccionada, ColorSeleccionado)
            VALUES (@UsuarioID, @ProductoID, @Cantidad, @TallaSeleccionada, @ColorSeleccionado);
        END
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        RAISERROR('Error al agregar al carrito', 16, 1);
    END CATCH
END;
GO
/****** Object:  StoredProcedure [dbo].[sp_AnularCompra]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[sp_AnularCompra]
    @CompraID INT
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE Compras SET Estado = 'Anulada' WHERE CompraID = @CompraID;
END;
GO
/****** Object:  StoredProcedure [dbo].[sp_CrearPedido]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[sp_CrearPedido]
    @ClienteID INT,
    @NombreCliente NVARCHAR(100),
    @EmailCliente NVARCHAR(100),
    @TelefonoCliente NVARCHAR(20),
    @DireccionEnvio NVARCHAR(255),
    @Ciudad NVARCHAR(100),
    @MetodoPago NVARCHAR(50),
    @Descuento DECIMAL(18,2) = 0,
    @Envio DECIMAL(18,2) = 0,
    @Notas NVARCHAR(MAX) = NULL,
    @PedidoID INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION;
    BEGIN TRY
        DECLARE @Subtotal DECIMAL(18,2);
        SELECT @Subtotal = ISNULL(SUM(c.Cantidad * p.PrecioVenta), 0)
        FROM Carrito c
        INNER JOIN Productos p ON c.ProductoID = p.ProductoID
        WHERE c.UsuarioID = @ClienteID;

        DECLARE @Total DECIMAL(18,2) = @Subtotal - @Descuento + @Envio;

        INSERT INTO Pedidos (
            ClienteID, NombreCliente, EmailCliente, TelefonoCliente,
            DireccionEnvio, Ciudad, MetodoPago,
            Subtotal, Descuento, Envio, Total, Notas
        )
        VALUES (
            @ClienteID, @NombreCliente, @EmailCliente, @TelefonoCliente,
            @DireccionEnvio, @Ciudad, @MetodoPago,
            @Subtotal, @Descuento, @Envio, @Total, @Notas
        );
        SET @PedidoID = SCOPE_IDENTITY();

        INSERT INTO PedidoDetalles (
            PedidoID, ProductoID, TallaID, ColorID,
            Cantidad, PrecioUnitario, Subtotal
        )
        SELECT
            @PedidoID, c.ProductoID, NULL, NULL,
            c.Cantidad, p.PrecioVenta, c.Cantidad * p.PrecioVenta
        FROM Carrito c
        INNER JOIN Productos p ON c.ProductoID = p.ProductoID
        WHERE c.UsuarioID = @ClienteID;

        UPDATE Productos
        SET Stock = Stock - c.Cantidad
        FROM Productos p
        INNER JOIN Carrito c ON p.ProductoID = c.ProductoID
        WHERE c.UsuarioID = @ClienteID;

        DELETE FROM Carrito WHERE UsuarioID = @ClienteID;

        INSERT INTO Ventas (
            ClienteID, FechaVenta, Subtotal, Descuento, Envio, Total, Estado, MetodoPago
        )
        VALUES (
            @ClienteID, GETDATE(), @Subtotal, @Descuento, @Envio, @Total, 'Completada', @MetodoPago
        );

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        RAISERROR('Error al crear pedido', 16, 1);
    END CATCH
END;
GO
/****** Object:  StoredProcedure [dbo].[sp_CreateCompra]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[sp_CreateCompra]
    @ProveedorID INT,
    @OrdenFactura NVARCHAR(50),
    @Fecha DATETIME,
    @Total DECIMAL(18,2),
    @Notas NVARCHAR(MAX) = NULL,
    @CompraID INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION;
    BEGIN TRY
        INSERT INTO Compras (ProveedorID, OrdenFactura, Fecha, Total, Estado, Notas)
        VALUES (@ProveedorID, @OrdenFactura, @Fecha, @Total, 'Activa', @Notas);
        SET @CompraID = SCOPE_IDENTITY();
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        RAISERROR('Error al crear compra', 16, 1);
    END CATCH
END;
GO
/****** Object:  StoredProcedure [dbo].[sp_CreateEmailVerification]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[sp_CreateEmailVerification]
    @UsuarioID INT,
    @Token NVARCHAR(500),
    @ExpiresAt DATETIME
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO EmailVerifications (UsuarioID, Token, ExpiresAt)
    VALUES (@UsuarioID, @Token, @ExpiresAt);
END;
GO
/****** Object:  StoredProcedure [dbo].[sp_CreatePasswordReset]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[sp_CreatePasswordReset]
    @Email NVARCHAR(100),
    @Token NVARCHAR(500),
    @ExpiresAt DATETIME,
    @UsuarioID INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT @UsuarioID = UsuarioID FROM Usuarios WHERE Email = @Email;
    IF @UsuarioID IS NULL
    BEGIN
        RAISERROR('Usuario no encontrado', 16, 1);
        RETURN;
    END
    INSERT INTO PasswordResetTokens (UsuarioID, Token, ExpiresAt)
    VALUES (@UsuarioID, @Token, @ExpiresAt);
END;
GO
/****** Object:  StoredProcedure [dbo].[sp_CreateProveedor]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[sp_CreateProveedor]
    @Nombre NVARCHAR(200),
    @Contacto NVARCHAR(100) = NULL,
    @Email NVARCHAR(100) = NULL,
    @Telefono NVARCHAR(50) = NULL,
    @Documento NVARCHAR(50) = NULL,
    @ProveedorID INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO Proveedores (Nombre, Contacto, Email, Telefono, Documento)
    VALUES (@Nombre, @Contacto, @Email, @Telefono, @Documento);
    SET @ProveedorID = SCOPE_IDENTITY();
END;
GO
/****** Object:  StoredProcedure [dbo].[sp_CreateRefreshToken]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[sp_CreateRefreshToken]
    @UsuarioID INT,
    @Token NVARCHAR(500),
    @ExpiresAt DATETIME,
    @IPAddress NVARCHAR(50) = NULL,
    @RefreshTokenID INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO RefreshTokens (UsuarioID, Token, ExpiresAt, IPAddress)
    VALUES (@UsuarioID, @Token, @ExpiresAt, @IPAddress);
    SET @RefreshTokenID = SCOPE_IDENTITY();
END;
GO
/****** Object:  StoredProcedure [dbo].[sp_ObtenerCarrito]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[sp_ObtenerCarrito]
    @UsuarioID INT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT
        c.CarritoID, c.ProductoID, p.Nombre, p.PrecioVenta, c.Cantidad,
        c.TallaSeleccionada, c.ColorSeleccionado,
        (p.PrecioVenta * c.Cantidad) AS Subtotal,
        p.ImagenPrincipal, c.FechaAgregado
    FROM Carrito c
    INNER JOIN Productos p ON c.ProductoID = p.ProductoID
    WHERE c.UsuarioID = @UsuarioID
    ORDER BY c.FechaAgregado DESC;

    SELECT SUM(p.PrecioVenta * c.Cantidad) AS Total
    FROM Carrito c
    INNER JOIN Productos p ON c.ProductoID = p.ProductoID
    WHERE c.UsuarioID = @UsuarioID;
END;
GO
/****** Object:  StoredProcedure [dbo].[sp_RegisterUser]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =====================================================
-- 8. PROCEDIMIENTOS ALMACENADOS
-- =====================================================

CREATE   PROCEDURE [dbo].[sp_RegisterUser]
    @NombreCompleto NVARCHAR(100),
    @Email NVARCHAR(100),
    @PasswordHash NVARCHAR(255),
    @RoleName NVARCHAR(50) = 'Cliente',
    @UsuarioID INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION;
    BEGIN TRY
        DECLARE @RoleID INT = (SELECT TOP 1 RoleID FROM Roles WHERE Nombre = @RoleName);
        IF @RoleID IS NULL
        BEGIN
            INSERT INTO Roles (Nombre, Descripcion, Estado) VALUES (@RoleName, @RoleName, 'activo');
            SET @RoleID = SCOPE_IDENTITY();
        END
        INSERT INTO Usuarios (NombreCompleto, Email, PasswordHash, RoleID, Estado)
        VALUES (@NombreCompleto, @Email, @PasswordHash, @RoleID, 'activo');
        SET @UsuarioID = SCOPE_IDENTITY();
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        RAISERROR('Error al registrar usuario', 16, 1);
    END CATCH
END;
GO
/****** Object:  StoredProcedure [dbo].[sp_RegistrarStockMovimiento]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[sp_RegistrarStockMovimiento]
    @ProductoID INT,
    @Cantidad INT,
    @Tipo NVARCHAR(20),
    @ReferenciaTipo NVARCHAR(50) = NULL,
    @ReferenciaID INT = NULL,
    @UsuarioID INT = NULL
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO StockMovimientos (ProductoID, Cantidad, Tipo, ReferenciaTipo, ReferenciaID, UsuarioID)
    VALUES (@ProductoID, @Cantidad, @Tipo, @ReferenciaTipo, @ReferenciaID, @UsuarioID);

    IF @Tipo = 'entrada'
        UPDATE Productos SET Stock = Stock + @Cantidad WHERE ProductoID = @ProductoID;
    ELSE IF @Tipo = 'salida'
        UPDATE Productos SET Stock = Stock - @Cantidad WHERE ProductoID = @ProductoID;
END;
GO
/****** Object:  StoredProcedure [dbo].[sp_ResetPassword]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[sp_ResetPassword]
    @Token NVARCHAR(500),
    @NewPasswordHash NVARCHAR(255),
    @Success BIT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SET @Success = 0;
    BEGIN TRANSACTION;
    BEGIN TRY
        DECLARE @UsuarioID INT = (
            SELECT TOP 1 UsuarioID FROM PasswordResetTokens
            WHERE Token = @Token AND ExpiresAt >= GETDATE() AND Used = 0
        );
        IF @UsuarioID IS NULL
        BEGIN
            RAISERROR('Token invalido o expirado', 16, 1);
            RETURN;
        END
        UPDATE Usuarios SET PasswordHash = @NewPasswordHash WHERE UsuarioID = @UsuarioID;
        UPDATE PasswordResetTokens SET Used = 1, UsedAt = GETDATE() WHERE Token = @Token;
        EXEC sp_RevokeAllUserTokens @UsuarioID;
        SET @Success = 1;
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        RAISERROR('Error al resetear contrasena', 16, 1);
    END CATCH
END;
GO
/****** Object:  StoredProcedure [dbo].[sp_RevokeAllUserTokens]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[sp_RevokeAllUserTokens]
    @UsuarioID INT
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE RefreshTokens SET Revoked = 1, RevokedAt = GETDATE()
    WHERE UsuarioID = @UsuarioID AND Revoked = 0;
END;
GO
/****** Object:  StoredProcedure [dbo].[sp_RevokeRefreshToken]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[sp_RevokeRefreshToken]
    @Token NVARCHAR(500)
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE RefreshTokens SET Revoked = 1, RevokedAt = GETDATE() WHERE Token = @Token;
END;
GO
/****** Object:  StoredProcedure [dbo].[sp_VerifyEmail]    Script Date: 1/07/2026 9:14:38 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[sp_VerifyEmail]
    @Token NVARCHAR(500)
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE EmailVerifications
    SET Verified = 1, VerifiedAt = GETDATE()
    WHERE Token = @Token AND ExpiresAt >= GETDATE();

    UPDATE Usuarios SET EmailVerificado = 1, Estado = 'activo'
    FROM Usuarios u
    INNER JOIN EmailVerifications ev ON ev.UsuarioID = u.UsuarioID
    WHERE ev.Token = @Token AND ev.ExpiresAt >= GETDATE();
END;
GO
USE [master]
GO
ALTER DATABASE [SelenneDB] SET  READ_WRITE 
GO
